// Generated by gencpp from file bucketbot_driver/CliffEvent.msg
// DO NOT EDIT!


#ifndef BUCKETBOT_DRIVER_MESSAGE_CLIFFEVENT_H
#define BUCKETBOT_DRIVER_MESSAGE_CLIFFEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bucketbot_driver
{
template <class ContainerAllocator>
struct CliffEvent_
{
  typedef CliffEvent_<ContainerAllocator> Type;

  CliffEvent_()
    : sensor(0)
    , state(0)
    , bottom(0)  {
    }
  CliffEvent_(const ContainerAllocator& _alloc)
    : sensor(0)
    , state(0)
    , bottom(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sensor_type;
  _sensor_type sensor;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _bottom_type;
  _bottom_type bottom;


    enum { LEFT = 0u };
     enum { CENTER = 1u };
     enum { RIGHT = 2u };
     enum { FLOOR = 0u };
     enum { CLIFF = 1u };
 

  typedef boost::shared_ptr< ::bucketbot_driver::CliffEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bucketbot_driver::CliffEvent_<ContainerAllocator> const> ConstPtr;

}; // struct CliffEvent_

typedef ::bucketbot_driver::CliffEvent_<std::allocator<void> > CliffEvent;

typedef boost::shared_ptr< ::bucketbot_driver::CliffEvent > CliffEventPtr;
typedef boost::shared_ptr< ::bucketbot_driver::CliffEvent const> CliffEventConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bucketbot_driver::CliffEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bucketbot_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bucketbot_driver': ['/home/pi/launchpad_base/src/bucketbot_driver/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bucketbot_driver::CliffEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bucketbot_driver::CliffEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bucketbot_driver::CliffEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f04b603e554ffcf2774053cae7927b6";
  }

  static const char* value(const ::bucketbot_driver::CliffEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f04b603e554ffcfULL;
  static const uint64_t static_value2 = 0x2774053cae7927b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bucketbot_driver/CliffEvent";
  }

  static const char* value(const ::bucketbot_driver::CliffEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LEFT=0\n\
uint8 CENTER=1\n\
uint8 RIGHT=2\n\
uint8 FLOOR=0\n\
uint8 CLIFF=1\n\
uint8 sensor\n\
uint8 state\n\
uint8 bottom\n\
";
  }

  static const char* value(const ::bucketbot_driver::CliffEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor);
      stream.next(m.state);
      stream.next(m.bottom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CliffEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bucketbot_driver::CliffEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bucketbot_driver::CliffEvent_<ContainerAllocator>& v)
  {
    s << indent << "sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "bottom: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bottom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUCKETBOT_DRIVER_MESSAGE_CLIFFEVENT_H
